# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compute_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='compute_service.proto',
  package='senseye.compute',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15\x63ompute_service.proto\x12\x0fsenseye.compute\x1a\x0c\x63ommon.proto2\xb1\x01\n\x07\x43ompute\x12S\n\x12\x41nalyzeVideoStream\x12\x1b.senseye.VideoStreamRequest\x1a\x1c.senseye.VideoStreamResponse(\x01\x30\x01\x12Q\n\x12\x41nalyzeVideoStatic\x12\x1b.senseye.VideoStaticRequest\x1a\x1c.senseye.VideoStreamResponse0\x01\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_COMPUTE = _descriptor.ServiceDescriptor(
  name='Compute',
  full_name='senseye.compute.Compute',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=57,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='AnalyzeVideoStream',
    full_name='senseye.compute.Compute.AnalyzeVideoStream',
    index=0,
    containing_service=None,
    input_type=common__pb2._VIDEOSTREAMREQUEST,
    output_type=common__pb2._VIDEOSTREAMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AnalyzeVideoStatic',
    full_name='senseye.compute.Compute.AnalyzeVideoStatic',
    index=1,
    containing_service=None,
    input_type=common__pb2._VIDEOSTATICREQUEST,
    output_type=common__pb2._VIDEOSTREAMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPUTE)

DESCRIPTOR.services_by_name['Compute'] = _COMPUTE

# @@protoc_insertion_point(module_scope)
