# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway_service.proto',
  package='senseye.gateway',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15gateway_service.proto\x12\x0fsenseye.gateway\x1a\x0c\x63ommon.proto2\xab\x01\n\x07Gateway\x12S\n\x12\x41nalyzeVideoStream\x12\x1b.senseye.VideoStreamRequest\x1a\x1c.senseye.VideoStreamResponse(\x01\x30\x01\x12K\n\x0c\x41nalyzeVideo\x12\x1b.senseye.VideoStaticRequest\x1a\x1c.senseye.VideoStreamResponse0\x01\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_GATEWAY = _descriptor.ServiceDescriptor(
  name='Gateway',
  full_name='senseye.gateway.Gateway',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=57,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='AnalyzeVideoStream',
    full_name='senseye.gateway.Gateway.AnalyzeVideoStream',
    index=0,
    containing_service=None,
    input_type=common__pb2._VIDEOSTREAMREQUEST,
    output_type=common__pb2._VIDEOSTREAMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AnalyzeVideo',
    full_name='senseye.gateway.Gateway.AnalyzeVideo',
    index=1,
    containing_service=None,
    input_type=common__pb2._VIDEOSTATICREQUEST,
    output_type=common__pb2._VIDEOSTREAMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GATEWAY)

DESCRIPTOR.services_by_name['Gateway'] = _GATEWAY

# @@protoc_insertion_point(module_scope)
