# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import compute_service_pb2 as compute__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway_service.proto',
  package='senseye.gateway',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15gateway_service.proto\x12\x0fsenseye.gateway\x1a\x15\x63ompute_service.proto2\xcb\x01\n\x07Gateway\x12\x63\n\x12\x41nalyzeVideoStream\x12#.senseye.compute.VideoStreamRequest\x1a$.senseye.compute.VideoStreamResponse(\x01\x30\x01\x12[\n\x0c\x41nalyzeVideo\x12#.senseye.compute.VideoStaticRequest\x1a$.senseye.compute.VideoStreamResponse0\x01\x62\x06proto3')
  ,
  dependencies=[compute__service__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_GATEWAY = _descriptor.ServiceDescriptor(
  name='Gateway',
  full_name='senseye.gateway.Gateway',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=66,
  serialized_end=269,
  methods=[
  _descriptor.MethodDescriptor(
    name='AnalyzeVideoStream',
    full_name='senseye.gateway.Gateway.AnalyzeVideoStream',
    index=0,
    containing_service=None,
    input_type=compute__service__pb2._VIDEOSTREAMREQUEST,
    output_type=compute__service__pb2._VIDEOSTREAMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AnalyzeVideo',
    full_name='senseye.gateway.Gateway.AnalyzeVideo',
    index=1,
    containing_service=None,
    input_type=compute__service__pb2._VIDEOSTATICREQUEST,
    output_type=compute__service__pb2._VIDEOSTREAMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GATEWAY)

DESCRIPTOR.services_by_name['Gateway'] = _GATEWAY

# @@protoc_insertion_point(module_scope)
