# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage_service.proto',
  package='senseye.storage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15storage_service.proto\x12\x0fsenseye.storage\"3\n\x0eStorageRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x03(\x0c\x12\x10\n\x08video_id\x18\x02 \x01(\t\"\"\n\x0fStorageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Z\n\x07Storage\x12O\n\nStoreVideo\x12\x1f.senseye.storage.StorageRequest\x1a .senseye.storage.StorageResponseb\x06proto3'
)




_STORAGEREQUEST = _descriptor.Descriptor(
  name='StorageRequest',
  full_name='senseye.storage.StorageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='senseye.storage.StorageRequest.content', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_id', full_name='senseye.storage.StorageRequest.video_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=93,
)


_STORAGERESPONSE = _descriptor.Descriptor(
  name='StorageResponse',
  full_name='senseye.storage.StorageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='senseye.storage.StorageResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['StorageRequest'] = _STORAGEREQUEST
DESCRIPTOR.message_types_by_name['StorageResponse'] = _STORAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StorageRequest = _reflection.GeneratedProtocolMessageType('StorageRequest', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEREQUEST,
  '__module__' : 'storage_service_pb2'
  # @@protoc_insertion_point(class_scope:senseye.storage.StorageRequest)
  })
_sym_db.RegisterMessage(StorageRequest)

StorageResponse = _reflection.GeneratedProtocolMessageType('StorageResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORAGERESPONSE,
  '__module__' : 'storage_service_pb2'
  # @@protoc_insertion_point(class_scope:senseye.storage.StorageResponse)
  })
_sym_db.RegisterMessage(StorageResponse)



_STORAGE = _descriptor.ServiceDescriptor(
  name='Storage',
  full_name='senseye.storage.Storage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=131,
  serialized_end=221,
  methods=[
  _descriptor.MethodDescriptor(
    name='StoreVideo',
    full_name='senseye.storage.Storage.StoreVideo',
    index=0,
    containing_service=None,
    input_type=_STORAGEREQUEST,
    output_type=_STORAGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGE)

DESCRIPTOR.services_by_name['Storage'] = _STORAGE

# @@protoc_insertion_point(module_scope)
