# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import storage_service_pb2 as storage__service__pb2


class StorageStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StoreVideo = channel.unary_unary(
        '/senseye.storage.Storage/StoreVideo',
        request_serializer=storage__service__pb2.StorageRequest.SerializeToString,
        response_deserializer=storage__service__pb2.StorageResponse.FromString,
        )


class StorageServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StoreVideo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StorageServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StoreVideo': grpc.unary_unary_rpc_method_handler(
          servicer.StoreVideo,
          request_deserializer=storage__service__pb2.StorageRequest.FromString,
          response_serializer=storage__service__pb2.StorageResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'senseye.storage.Storage', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
